### ISSUE TITLE
"Stop on uncaught exception" in node v0.10

### ISSUE THREAD

**Issue by iliakan** [node-inspector/node-inspector#190]
I created a file e.js with a single line:

```
blabla();
```

Now I run node 0.10.15 & latest node-inspector

```
node --debug-brk e.js
node-inspector
```

Then I go to Chrome, see that the execution is stopped and enable the violet(not blue!) "stop on error" button below http://screencast.com/t/ayFC8O31lVWg 

Then I click "continue" and the script dies. 

Expected behavior: stop execution on error.
Previous version of node-inspector: works as expected
Chrome built-in: works as expected
Node-inspector 0.3.2: fails.

Important stuff for debugging, it seems.

**Comment by rainabba** [comment]
Sorry to use a closed issue, but I can't find anyting on HOW to made node-inspector stop on unhanded exceptions, only talk about it happening and the README saying it can. Do I need to enable an option or take other steps? Using Node 12.0 and can otherwise debug.

**Comment by bajtos** [comment]
@rainabba IIRC, the support for stopping on unhandled exceptions in Node.js is rather fragile and may be broken in certain versions. Also keep in mind that unhandled exception = exception that crashes your process. If you catch unhandled exceptions e.g. via domains, they are no longer considered as uncaught (IIRC).

In order to help you more, I need an example app reproducing the problem that I can run on my machine.
