### ISSUE TITLE
Slow Startup

### ISSUE THREAD

**Issue by agebrock** [node-inspector/node-inspector#237]
Hi there, 

i am working on a big node.js application, currently the debugger requires about one Minute to finish loading. To improve the startup time i sometimes clear local caches but this helps only a little.

Is there any way to improve speed ? Maybe exclude files or something ? 

Thx 

---

What needs to be implemented to resolve this issue:
1. Modify ScriptFileStorage to cache results of glob searches by reusing the glob cache object (see https://npmjs.org/package/glob for details).
2. Add a new config option to disable findAllApplicationScripts - see [lib/ScriptFileStorage.js](https://github.com/node-inspector/node-inspector/blob/master/lib/ScriptFileStorage.js#L174)
3. Add a new config option to disable sourceMap detection - see [lib/ScriptManager.js](https://github.com/node-inspector/node-inspector/blob/master/lib/ScriptManager.js#L144)

**Comment by voidcode** [comment]
Try reload `http://127.0.0.1:8080/debug?port=5858`
After.
`node-debug <appname.js>`
Then the debugger starts instantly, on my system.

**Comment by totty90** [comment]
@voidcode doesn't help much, I also use that trick, but is still not as fast as I like.

**Comment by totty90** [comment]
@3y3 and then what? where are the logs? no file is created nor the cli program outputs anything.

**Comment by jmm** [comment]
@bajtos 
With `node-inspector@0.12.2` / `node@0.10.32` on Linux, it takes a long time to load initially, then takes *forever* to proceed (after resuming from being paused on the first line), while logging these entries:

```
backend: {"method":"Debugger.scriptParsed"
```

(To get that output I had to hack one of the files as described in https://github.com/node-inspector/node-inspector/issues/671#issuecomment-114200212.)

How do I:

> [[disable] dispatch of this event in the front-end](https://github.com/node-inspector/node-inspector/issues/237#issuecomment-27399120)

? And what consequences will that have?

Is that what this [reference to `front-end/InspectorBackend.js`](https://github.com/node-inspector/node-inspector/issues/237#issuecomment-27286308) line 44 and 45 relates to? Please always make links like that to the permalink URL.

**Comment by bajtos** [comment]
> How do I [disable] dispatch of this event in the front-end

You need to modify the code in `front-end` directory, most likely [front-end/sdk/InspectorBackend.js](https://github.com/node-inspector/node-inspector/blob/abc1d621473ca41563f7ddbc1f69422457f41784/front-end/sdk/InspectorBackend.js). I don't have enough time to try this myself now, sorry for that :(

> what consequences will that have?

IIRC, when you disable `Debugger.scriptParsed` events, the front-end will not know about your source files. I am not sure about the exact behaviour, in the worst case you won't be able to debug at all, because there will be no source code in the UI to show.

**Comment by jmm** [comment]
@bajtos Thanks, sorry for the delay replying. I'll have to poke around sometime. So that's probably just going to identify a bottleneck, but not actually work around it I guess.

**Comment by danielmanesku** [comment]
I am debugging a grunt task with node-inspector, and because my project contains a lot of dependencies, startup time is about 4-5 mins. 
Adding `--no-preload` boosts the startup time to 2-3 s, but my breakpoint is not hit. I guess that script finishes before node-inspector gets a chance to break it.

Fortunately, I found a solution for this: add in your script `debugger;` and node-inspector will stop there.

**Comment by 3y3** [comment]
@danielmanesku , how about `--debug-brk` option?

**Comment by danielmanesku** [comment]
@3y3 If I run into one shell `node-inspector` and in another `node --debug-brk /usr/local/bin/grunt myTask`, startup time is long, about 4-5 min. Am I missing something?

**Comment by moander** [comment]
Try preload:false instead of no-preload:true if using a rc file or similar:
```
{
  "preload": false
}
```

**Comment by ericelliott** [comment]
It's unusably slow for me in Node Inspector v0.12.8 using `node-inspector --preload=false` (or with no optional arguments).
