### ISSUE TITLE
Feature Request: Network Tab?

### ISSUE THREAD

**Issue by go1dfish** [node-inspector/node-inspector#341]
Not sure how realistic this is as I'm not familiar with the internal structure of node.js wrt http requests.

But if it were possible for node-inspector to implement something like Chrome's Network tab for the debugging of outgoing/incoming http requests this would be very powerful.

**Comment by hshepherd** [comment]
+1

**Comment by petercsoka** [comment]
+1

**Comment by jkrems** [comment]
Some older implementation open for grabs/porting:

* The injected code: https://github.com/jkrems/bugger/blob/master/src/bug-script/probes/network.coffee
* The inspector/agent side: https://github.com/jkrems/bugger/blob/master/src/domains/Network.coffee

**Comment by marcominetti** [comment]
:+1:

**Comment by jkrems** [comment]
(Sorry, didn't see that the file was actually already linked above.)

**Comment by jkrems** [comment]
The newer / nicer version is here: https://github.com/buggerjs/bugger-agents/blob/master/lib/agents/network.probe.js

Working on porting it now. But just in case I get distracted and someone else wants to take this on.

**Comment by marcominetti** [comment]
:+1:

**Comment by atif089** [comment]
@jkrems I was building a web scraper and I have a read world scenario to try this out. Can you please help me how to merge your code with my copy of module to try this? (I'm assuming I can't do a git cherry-pick or something like that because the module itself is not a git repo)


Alternatively, the repo where I want to try this is here https://github.com/atif089/RandomActsOfTech/tree/master/InstaUserScraper

**Comment by 3y3** [comment]
Closed in #677
