### ISSUE TITLE
Cannot set breakpoints in module loaded with npm link

### ISSUE THREAD

**Issue by overlookmotel** [node-inspector/node-inspector#370]
I'm developing a module which sits in a folder outside of the application that I'm debugging. i.e.:
Application is at `/work/the-app/`
Module is at `/work/modules/the-module/`

I include the module into the app using `npm link`, which creates a symlink from `/work/modules/the-module/` to `/work/the-app/node_modules/the-module/`

When debugging with node-inspector, breakpoints set in the linked module are skipped over. Is it possible to debug the module like this?

Mac OS X Mountain Lion 10.8.5, node v0.10.26, node-inspector v0.7.3

**Comment by bajtos** [comment]
FWIW, the glob module can follow symlinks since v4.5.0 and v5.0.0, see https://github.com/isaacs/node-glob/pull/148.

**Comment by sonewman** [comment]
Nice :+1:

**Comment by gxela** [comment]
This is still an issue, I am not able to debug a node module that was npm link'd into the project, the project is run from docker containers. Am able to debug node.js app running in docker container with vscode and WebStorm, but not able to set a breakpoint in code that is npm link'd into the project. Let me know if you need an example dockerfile, I can write one up for you. This issue should still be open because it's still an issue.

**Comment by iyobo** [comment]
This was working for me until just last week all of a sudden. had been using Webstorm 2017 all year and it was working. Never upgraded. It just....stopped...using breakpoints in npm-linked moduled.

Breakpoints stop in node_modules that are NOT npm-linked however....so there's definitely something weird about how it reads links.

Perhaps it might even be an OS level "update" change that screwed things up (osx)? I'm still investigating.

**Comment by huiwang** [comment]
I resolved this by running node with --preserve-symlinks
