### ISSUE TITLE
Running node-inspector with Gulp

### ISSUE THREAD

**Issue by MadLittleMods** [node-inspector/node-inspector#447]
How do I debug a gulp task?

How do I debug a global CLI command like `gulp` or `gulp task`?

This does not work: `node-debug gulp`

I saw the [documentation on Mocha](https://github.com/node-inspector/node-inspector#how-do-i-debug-mocha-unit-tests) but I am not sure if there is a similar thing for Gulp. There is also [another issue about Gulp](https://github.com/node-inspector/node-inspector/issues/348) but the solution given uses `which` and not sure it even works.

**Update:**
I figured out that the `node-debug $(which gulp) task` command suggested in the [other issue about gulp](https://github.com/node-inspector/node-inspector/issues/348) uses a unix only $(which) statement that gets replaced with the full path to the gulp-cli.

In Windows you would have to get the full path of gulp to make an equivalent command:
`node-debug "C:\Users\user\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js" task`
_You can omit the `task` part to run the `default` task._

I misunderstood Node Inspector's capabilities and thought `console.log` calls showed up in the node-inspector console. I now know that it is only a REPL client and doesn't output the CMD prints.

**Comment by OnkelTem** [comment]
I don't get how to debug anything form gulp.
When I run ```node-debug /usr/local/bin/gulp task```, I can't set a working breakpoint anywhere.
If I add 'debugger;' line in gulpfilejs, debugger doesn't stop at it, instead is opens up some ramdom file (module.js)  - https://sc-cdn.scaleengine.net/i/063ef970096a12501c4569595b4a23bf.png in a ramdom line.

Please, can you *describe* how to use you debugger?

**Comment by OnkelTem** [comment]
This is what I also tried.

(1)
```
$ node-inspector 
Node Inspector v0.9.2
Visit http://127.0.0.1:8080/debug?port=5858 to start debugging.
```

I open the url and see empty UI. 

(2)
```
$ node --debug-brk /usr/local/bin/gulp jade
Debugger listening on port 5858
```

Both processes are suspended, I see no output either in node-inspector (1) or node (2) stdouts.
UI is not updated either and is empty.
Since I have no other options, I reload UI with Ctrl-R, after that:
* UI start showing some files (similar to what is on the screenshot I posted before)
* (2) resumes till the end - i.e. 'jade' task runs w/o any breakpoints or visualization in UI

Now when I open gulpfile.js in UI, I can't set any breakpoint as clicking on left margin makes nothing:
https://sc-cdn.scaleengine.net/i/c53d0a35a7e61a4f9961e537314748ca.png

I'm out of ideas.
