### ISSUE TITLE
Weird error on start

### ISSUE THREAD

**Issue by rumkin** [node-inspector/node-inspector#754]
When I run Node Inspector in docker container with alpine linux I've got error message in console:

```
Error: Error relocating /node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v46-linux-x64/profiler.node: __sprintf_chk: symbol not found
```

Alpine Linux 3.2
node v4.1
node-inspector v0.12.3

**Comment by 3y3** [comment]
Looks like a problem on level below.
@rvagg, if this isn't problem on nan, can you retarget it to node team.

If I understand right in this case problem happens with prebuilt binaries builded on Ubuntu (TravisCI uses Ubuntu?). This can be a source of problems?

**Comment by rumkin** [comment]
@3y3 Yep, I think building on Ubuntu could be the source of problems.

**Comment by 3y3** [comment]
@rumkin , can you try
```
sudo npm i -g node-inspector --build-from-source --unsafe-perm
```
it can be helpful

**Comment by rvagg** [comment]
This is a tricky one because v8-profiler is probably building using a much newer libc and libc++ than comes with the default ubuntu 12.04 that travis runs on and v8-profiler is being compiled with a link to that version. I honestly don't know anything about why it's `sprintf` that it's complaining about, perhaps switching to `snprintf` in v8-profiler will help..

**Comment by rumkin** [comment]
Great! Option `--build-from-source` solved the issue!
Thanks.
:+1:
