### ISSUE TITLE
Module doesn't exits

### ISSUE THREAD

**Issue by nidazehraa** [node-inspector/node-inspector#770]
Error: Cannot find module '/opt/local/node-v0.12.0-linux-x64/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v14-linux-x64/debug.node'
Instead node-v11-linux-x64/debug.node' exists in this directory.
Following are the versions that I have installed on my system:
node -v
v0.12.0
node-inspector -v
 v0.12.3
npm -v 
2.5.1
I have tried to run the npm run install in v8-debug and v8-profiler but the error still persists.
Any Help please ???

**Comment by nikmartin** [comment]
I got the same error, and had to do:
`npm -g uninstall node-inspector && npm -g install node-inspector` to force node-inspector to rebuild the modules it needs to link tt he new version of the V8 debugger

**Comment by 3y3** [comment]
Are you using `nvm`?

This situation happens if you have two different node versions installed on your machine (one default and one other with help of nvm).
One other case - you update your node version, but miss to update your global dependencies. It is important because some modules (for example `node-inspector`) have some c++ addons, which need to be rebuilded for new node version.

**Comment by 3y3** [comment]
Try to install 0.12.5. This version includes prebuilt binaries for all actual node versions from the box.
Feel free to reopen this issue if it still exist.
