### ISSUE TITLE
not working with new version  nodejs  6.4.0+

### ISSUE THREAD

**Issue by liaolunhui** [node-inspector/node-inspector#928]
![image](https://cloud.githubusercontent.com/assets/13741751/18701292/75f81d44-800e-11e6-85e1-417b4496fc06.png)

**Comment by liaolunhui** [comment]
please consider  the compatibility

**Comment by ubaidseth** [comment]
Any alternative?

**Comment by liaolunhui** [comment]
I am using nodejs 6.3.1 to avoid the problem.
But in the future , I hope to use new version of nodejs.

**Comment by vird** [comment]
Try this hack/workaround
Seek in /usr/lib64/node_modules/node-inspector/lib/InjectorClient.js (your location of node-inspector)
Look at
Function InjectorClient.prototype._getFuncWithNMInScope

Replace this

    cb(null, result.handle);

with this

    cb(null, result.constructorFunction.ref);

I have this message in node-ispector console tab

    Internal error: TypeError: Cannot read property '0' of undefined

But breakpoints and other stuff works.
Tested with 6.6.0

**P.s.**
Seems node-inspector method for retrieval NativeModule link fails to handle -1 even with https://github.com/node-inspector/node-inspector/pull/906 or similar because this solves problem with response, but not with request.
You will recieve this message

    Error: No NativeModule in target scope

and you will not able to go through breakpoints with node-inspector's UI.

**Comment by 15920353089** [comment]
@vird yes,it's work,but breakpoints can't work

**Comment by RocketRooster** [comment]
Dudes! Please get this fixed!

I would take the Ring to Mordor myself, but I don't know the way. We're relying on your know-how!

**Comment by mightyiam** [comment]
The situation is, that with Node v6 point something, you don't need all this:
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.hkrhparu1

**Comment by RocketRooster** [comment]
The --inspect flag has never worked for me. I just get empty inspectors and a blank file list for the supplied debug URL. I know the debugger is active because I get the "Listening on port 9229, warning it's experimental etc" message on stdout but no luck. My chrome is up to date, or so it says.

I'm developing and debugging on Windows while serving on Ubuntu, but I would be surprised if this would make a difference.

**Comment by mightyiam** [comment]
@RocketRooster this is going off-topic for this repository. Try the Node.JS mailing list?

**Comment by hustxiaoc** [comment]
The issue has been resolved, try `node-inspector@1.0.0` please!

**Comment by RocketRooster** [comment]
Yay, it's working. Thanks, guys, you are champions.
