### ISSUE TITLE
it failed when i run this tool

### ISSUE THREAD

**Issue by zzzgit** [node-inspector/node-inspector#969]
![image](https://cloud.githubusercontent.com/assets/1060733/22068858/527f72d8-ddd1-11e6-8489-0891bf701ea0.png)

and another question,i uninstalled this package and rerun npm install -g node-inspector,version 0.12.8 will be installed instead of the last version

**Comment by ryanone** [comment]
I see this too, when using Node 6.4 and above.  However, this is fixed with https://github.com/node-inspector/node-inspector/commit/2e5309f75099753740c4567e17fd79ee27885d71

A new release just needs to get published to NPM.  In the meantime though, you can clone the repo locally, and run node-debug by calling `./bin/node-debug.js [path to your file]`.  That worked for me.  Hopefully that works for you.

**Comment by atrauzzi** [comment]
Seems like I might be encountering this issue as well.

**Comment by hustxiaoc** [comment]
Try `node-inspector@1.0.0` please.
